INSERT INTO y2_clinical_9.admin VALUES(1,'R', 'Chand','rchand','pass');
INSERT INTO y2_clinical_9.admin VALUES(2,'L', 'V','lv','pass');
INSERT INTO y2_clinical_9.admin VALUES(3,'James', 'Woods','j_woods','pass');
INSERT INTO y2_clinical_9.admin VALUES(4,'T', 'Sabir','tSabir','pass');
INSERT INTO y2_clinical_9.questionnaire VALUES (1,'Personal Information', 'Please enter your personal information as accurately as possible','2017-02-19',1);
INSERT INTO y2_clinical_9.questionnaire VALUES (2,'Next of Kin Information','Please enter your next of kin information as accurately as possible','2017-02-20',2);
INSERT INTO y2_clinical_9.questionnaire VALUES (3,'Financial Information','Please enter your finanial information as accurately as possible','2017-02-20',3);
INSERT INTO y2_clinical_9.questionnaire VALUES (4,'Accomodation Information','Please enter your accodation information as accurately as possible','2017-02-20',4);
INSERT INTO y2_clinical_9.question VALUES (1,'Enter your first name', 2, 1);
INSERT INTO y2_clinical_9.question VALUES (2,'Enter your last name', 2, 1);
INSERT INTO y2_clinical_9.question VALUES (3,'What is your gender?', 1, 1);
INSERT INTO y2_clinical_9.question VALUES (4,'How can we contact you?', 4, 1);
INSERT INTO y2_clinical_9.question VALUES (5,'Enter first name', 2, 2);
INSERT INTO y2_clinical_9.question VALUES (6,'Enter surname', 2, 2);
INSERT INTO y2_clinical_9.question VALUES (7,'What is the nature of your relationship?', 1, 2);
INSERT INTO y2_clinical_9.question VALUES (8,'How can we contact your next of kin?', 4, 2);
INSERT INTO y2_clinical_9.question VALUES (9,'Enter your annual income', 2, 3);
INSERT INTO y2_clinical_9.question VALUES (10,'Do you have children?', 1, 3);
INSERT INTO y2_clinical_9.question VALUES (11,'Please describe any other sources of income other than salary', 3, 3);
INSERT INTO y2_clinical_9.question VALUES (12,'Enter your annual expenditures', 2, 3);
INSERT INTO y2_clinical_9.question VALUES (13,'What are your living arrangements?', 1, 4);
INSERT INTO y2_clinical_9.question VALUES (14,'How many people do you live with?', 2, 4);
INSERT INTO y2_clinical_9.question VALUES (15,'Enter the address', 3, 4);
INSERT INTO y2_clinical_9.options VALUES (1,'Male', 1, 3);
INSERT INTO y2_clinical_9.options VALUES (2,'Female', 2, 3);
INSERT INTO y2_clinical_9.options VALUES (3,'E-mail', 1, 4);
INSERT INTO y2_clinical_9.options VALUES (4,'Telephone', 2, 4);
INSERT INTO y2_clinical_9.options VALUES (5,'Post', 3, 4);
INSERT INTO y2_clinical_9.options VALUES (6,'Mother', 1, 7);
INSERT INTO y2_clinical_9.options VALUES (7,'Father', 2, 7);
INSERT INTO y2_clinical_9.options VALUES (8,'Spouse', 3, 7);
INSERT INTO y2_clinical_9.options VALUES (9,'Sibling', 4, 7);
INSERT INTO y2_clinical_9.options VALUES (10,'E-mail', 1, 8);
INSERT INTO y2_clinical_9.options VALUES (11,'Telephone', 2, 8);
INSERT INTO y2_clinical_9.options VALUES (12,'Post', 3, 8);
INSERT INTO y2_clinical_9.options VALUES (13,'Yes', 1, 10);
INSERT INTO y2_clinical_9.options VALUES (14,'No', 1, 10);
INSERT INTO y2_clinical_9.options VALUES (15,'Living with parents', 1, 13);
INSERT INTO y2_clinical_9.options VALUES (16,'Own a home', 2, 13);
INSERT INTO y2_clinical_9.options VALUES (17,'Renting', 3, 13);
INSERT INTO y2_clinical_9.options VALUES (18,'Living away from home (Student)', 4, 13);

