INSERT INTO y2_clinical_9.admin VALUES(1,'R', 'Chand','rchand','pass');
INSERT INTO y2_clinical_9.admin VALUES(2,'L', 'V','lv','pass');
INSERT INTO y2_clinical_9.admin VALUES(3,'James', 'Woods','j_woods','pass');
INSERT INTO y2_clinical_9.admin VALUES(4,'T', 'Sabir','tSabir','pass');
INSERT INTO y2_clinical_9.questionnaire VALUES (1,'questionnaire_title_1','questionnaire_description_1','2017-02-19',1);
INSERT INTO y2_clinical_9.questionnaire VALUES (2,'questionnaire_title_2','questionnaire_description_2','2017-02-20',2);
INSERT INTO y2_clinical_9.questionnaire VALUES (3,'questionnaire_title_3','questionnaire_description_3','2017-02-20',3);
INSERT INTO y2_clinical_9.questionnaire VALUES (4,'questionnaire_title_4','questionnaire_description_4','2017-02-20',4);
INSERT INTO y2_clinical_9.question VALUES (1,'Question 1 in Questionnaire 1', 1, 1);
INSERT INTO y2_clinical_9.question VALUES (2,'Question 2 in Questionnaire 1', 2, 1);
INSERT INTO y2_clinical_9.question VALUES (3,'Question 3 in Questionnaire 1', 3, 1);
INSERT INTO y2_clinical_9.question VALUES (4,'Question 4 in Questionnaire 1', 4, 1);
INSERT INTO y2_clinical_9.question VALUES (5,'Question 1 in Questionnaire 2', 1, 2);
INSERT INTO y2_clinical_9.question VALUES (6,'Question 2 in Questionnaire 2', 2, 2);
INSERT INTO y2_clinical_9.question VALUES (7,'Question 3 in Questionnaire 2', 3, 2);
INSERT INTO y2_clinical_9.question VALUES (8,'Question 4 in Questionnaire 2', 4, 2);
INSERT INTO y2_clinical_9.question VALUES (9,'Question 1 in Questionnaire 3', 1, 3);
INSERT INTO y2_clinical_9.question VALUES (10,'Question 2 in Questionnaire 3', 2, 3);
INSERT INTO y2_clinical_9.question VALUES (11,'Question 3 in Questionnaire 3', 3, 3);
INSERT INTO y2_clinical_9.question VALUES (12,'Question 4 in Questionnaire 3', 4, 3);
INSERT INTO y2_clinical_9.question VALUES (13,'Question 1 in Questionnaire 4', 1, 4);
INSERT INTO y2_clinical_9.question VALUES (14,'Question 2 in Questionnaire 4', 2, 4);
INSERT INTO y2_clinical_9.question VALUES (15,'Question 3 in Questionnaire 4', 3, 4);
INSERT INTO y2_clinical_9.question VALUES (16,'Question 4 in Questionnaire 4', 4, 4);
INSERT INTO y2_clinical_9.options VALUES (1,'Radio answer 1', 1, 1);
INSERT INTO y2_clinical_9.options VALUES (2,'Radio answer 2', 2, 1);
INSERT INTO y2_clinical_9.options VALUES (3,'Single Line answer', null, 2);
INSERT INTO y2_clinical_9.options VALUES (4,'Multi-Line Answer 1', null, 3);
INSERT INTO y2_clinical_9.options VALUES (8,'Multiple choice answer 1', 1, 4);
INSERT INTO y2_clinical_9.options VALUES (9,'Multiple choice answer 2', 2, 4);
INSERT INTO y2_clinical_9.options VALUES (10,'Multiple choice answer 3', 3, 4);
INSERT INTO y2_clinical_9.options VALUES (11,'Multiple choice answer 4', 4, 4);