-- MySQL Script generated by MySQL Workbench
-- 11/17/17 12:14:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Y2_Clinical_9
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Y2_Clinical_9
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Y2_Clinical_9` DEFAULT CHARACTER SET utf8 ;
USE `Y2_Clinical_9` ;

-- -----------------------------------------------------
-- Table `Y2_Clinical_9`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Y2_Clinical_9`.`Admin` (
  `AdminID` INT NOT NULL,
  `First_Name` VARCHAR(45) NULL,
  `Last_Name` VARCHAR(45) NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Y2_Clinical_9`.`Questionnaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Y2_Clinical_9`.`Questionnaire` (
  `QuestionnaireID` INT NOT NULL,
  `Questionnaire_Title` TEXT NULL,
  `Questionnaire_Descriptionl` TEXT NULL,
  `Date_Created` DATETIME NULL,
  PRIMARY KEY (`QuestionnaireID`),
  CONSTRAINT `AdminID`
    FOREIGN KEY ()
    REFERENCES `Y2_Clinical_9`.`Admin` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Y2_Clinical_9`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Y2_Clinical_9`.`Question` (
  `QuestionID` INT NOT NULL,
  `Question_Description` TEXT NULL,
  PRIMARY KEY (`QuestionID`),
  CONSTRAINT `QuestionnaireID`
    FOREIGN KEY ()
    REFERENCES `Y2_Clinical_9`.`Questionnaire` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Y2_Clinical_9`.`Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Y2_Clinical_9`.`Option` (
  `OptionID` INT NOT NULL,
  `Option_Descriptipn` TEXT NULL,
  `Option_Type` VARCHAR(45) NULL,
  PRIMARY KEY (`OptionID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Y2_Clinical_9`.`Question_Option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Y2_Clinical_9`.`Question_Option` (
  `Question_Option_ID` INT NOT NULL,
  PRIMARY KEY (`Question_Option_ID`),
  CONSTRAINT `QuestionID`
    FOREIGN KEY ()
    REFERENCES `Y2_Clinical_9`.`Question` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OptionID`
    FOREIGN KEY ()
    REFERENCES `Y2_Clinical_9`.`Option` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
